// UI Constants
export const COLORS = {
  gradient: {
    primary: 'from-blue-600 to-indigo-600',
    success: 'from-green-600 to-emerald-600',
    warning: 'from-orange-600 to-amber-600',
    danger: 'from-red-600 to-rose-600',
  },
  badge: {
    green: 'bg-green-100 text-green-800',
    blue: 'bg-blue-100 text-blue-800',
    orange: 'bg-orange-100 text-orange-800',
    red: 'bg-red-100 text-red-800',
    yellow: 'bg-yellow-100 text-yellow-800',
  },
} as const;

// Text Constants (Indonesian)
export const TEXT = {
  common: {
    loading: 'Memuat...',
    save: 'Simpan',
    cancel: 'Batal',
    back: 'Kembali',
    logout: 'Keluar',
    login: 'Masuk',
    processing: 'Memproses...',
    close: 'Tutup',
    clear: 'Hapus',
    compare: 'Bandingkan',
    view: 'Lihat',
    add: 'Tambah',
    remove: 'Hapus',
    export: 'Ekspor',
    search: 'Cari',
  },
  dashboard: {
    welcome: 'Selamat Datang',
    summary: 'Ringkasan karier Anda hari ini',
    meritScore: 'Skor Merit',
    profile: 'Profil',
    careerProgress: 'Progres Karier',
    complete: 'Lengkap',
    currentPosition: 'Saat Ini',
    targetPosition: 'Target',
    nextMilestone: 'Milestone Berikutnya',
    viewCareerGPS: 'Lihat Career GPS',
    recommendations: 'Rekomendasi untuk Anda',
    trainingPrograms: 'Program Pelatihan',
    enrollNow: 'Daftar Sekarang',
    myTraining: 'Pelatihan Saya',
    careerPath: 'Jalur Karier Anda',
    towards: 'menuju',
    completeTraining: 'Selesaikan Pelatihan Leadership',
    enrolled: 'Terdaftar',
    yourProgress: 'Progress Anda',
    startLearning: 'Mulai Belajar',
    continueLearning: 'Lanjutkan Belajar',
    certificate: 'Sertifikat',
  },
  login: {
    email: 'Email',
    password: 'Kata Sandi',
    demoAccounts: 'Akun Demo (Klik untuk coba)',
    prototypeNotice: 'Prototipe Demo - Semua fitur disimulasikan. Data tidak tersimpan permanen.',
    signIn: 'Masuk ke Akun Anda',
    enterCredentials: 'Masukkan kredensial Anda untuk mengakses dashboard',
    signInButton: 'Masuk',
    asn: 'ASN',
    supervisor: 'Supervisor',
    committee: 'Komite',
  },
  careerGps: {
    title: 'Career GPS',
    subtitle: 'Rekomendasi Karier yang Dipersonalisasi oleh AI',
    currentRole: 'Peran Saat Ini',
    targetRole: 'Target Karier',
    matchPercentage: 'Persentase Kesesuaian',
    estimatedTimeline: 'Estimasi Waktu',
    months: 'bulan',
    successRate: 'Tingkat Keberhasilan',
    aiConfidence: 'Keyakinan AI',
    competencyGaps: 'Kesenjangan Kompetensi',
    current: 'Saat Ini',
    required: 'Dibutuhkan',
    gap: 'Kesenjangan',
    points: 'poin',
    actionPlan: 'Rencana Aksi',
    priority: 'Prioritas',
    high: 'Tinggi',
    medium: 'Sedang',
    low: 'Rendah',
    duration: 'Durasi',
    impact: 'Dampak',
    aiInsights: 'Wawasan AI',
    recommendedPath: 'Jalur yang Direkomendasikan',
    keyStrengths: 'Kekuatan Utama',
    areasForGrowth: 'Area untuk Berkembang',
    nextSteps: 'Langkah Selanjutnya',
  },
  supervisor: {
    title: 'Dashboard Tim',
    teamSize: 'Ukuran Tim',
    activeMembers: 'Anggota Aktif',
    avgMeritScore: 'Skor Merit Rata-rata',
    outOf: 'Dari',
    topPerformer: 'Kinerja Terbaik',
    merit: 'Merit',
    yourTeam: 'Anggota Tim Anda',
    rank: 'Peringkat',
    trainings: 'Pelatihan',
    progress: 'Progres',
    competencies: 'Kompetensi',
    trainingProgress: 'Progres Pelatihan',
    completed: 'Selesai',
    certifications: 'Sertifikasi',
    careerTarget: 'Target Karier',
    target: 'Target',
    recommendForPromotion: 'Rekomendasikan untuk Promosi',
    sendFeedback: 'Kirim Umpan Balik',
    selectMember: 'Pilih anggota tim untuk melihat detail',
    noTeamMembers: 'Tidak ada anggota tim ditemukan',
  },
  meritBoard: {
    title: 'Merit Intelligence Dashboard',
    directorPosition: 'Posisi Direktur - Kandidat Promosi',
    totalCandidates: 'Total Kandidat',
    reviewDue: 'Tenggat Tinjauan',
    liveDataActive: 'Data Live Aktif',
    view: 'Tampilan',
    sortBy: 'Urutkan',
    allCandidates: 'Semua Kandidat',
    supervisorsOnly: 'Hanya Supervisor',
    asnOnly: 'Hanya ASN',
    meritScoreHighLow: 'Skor Merit (Tinggi ke Rendah)',
    nameAZ: 'Nama (A-Z)',
    exportReport: 'Ekspor Laporan',
    candidates: 'Kandidat',
    match: 'Kecocokan',
    tenure: 'Masa Kerja',
    years: 'tahun',
    meritScore: 'Skor Merit',
    merit: 'Merit',
    meritScoreBreakdown: 'Rincian Skor Merit',
    competencyMatch: 'Kecocokan Kompetensi',
    performance: 'Kinerja',
    feedback360: 'Umpan Balik 360°',
    learningAgility: 'Agilitas Belajar',
    aiJustification: 'Justifikasi AI',
    biasCheck: 'Pemeriksaan Bias',
    noBiasDetected: 'Tidak terdeteksi bias demografis di gender, usia, dan faktor regional.',
    teamMembers: 'Anggota Tim',
    addToShortlist: 'Tambah ke Daftar Pendek',
    addToCompare: 'Tambah ke Perbandingan',
    removeFromCompare: 'Hapus dari Perbandingan',
    compareFull: 'Perbandingan Penuh',
    selectCandidate: 'Pilih kandidat untuk melihat detail',
    compareList: 'Daftar Perbandingan',
    compareNow: 'Bandingkan Sekarang',
    candidateComparison: 'Perbandingan Kandidat',
    reportsTo: 'Lapor kepada',
    team: 'Tim',
    members: 'anggota',
    avgMerit: 'Rata-rata Merit',
    training: 'Pelatihan',
    programs: 'program',
    aiComparisonSummary: 'Ringkasan Perbandingan AI',
    hasAMeritScore: 'memiliki skor merit',
    comparedTo: 'dibandingkan dengan',
    leadsBy: 'unggul',
    equalScores: 'Skor merit setara',
    closeComparison: 'Perbandingan dekat',
    exportComparisonReport: 'Ekspor Laporan Perbandingan',
    completedTrainings: 'Pelatihan Selesai',
    supervisor: 'SUPERVISOR',
  },
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
} as const;

// Animation Durations
export const ANIMATION = {
  fast: '150ms',
  normal: '300ms',
  slow: '500ms',
} as const;
